version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petlove-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    # volumes:
      # - .:/app

volumes:
  mongo-data:
