recuperar_contexto:
  description: >
    Reformule a mensagem do usuário em uma pergunta objetiva e específica para buscar produtos relevantes no banco vetorial. \n
    mensagem do usuário: '{user_input}'
    Utilize dados como animal e raça, se disponíveis, para aumentar a precisão.
    Realize no máximo 2 tentativas de reformulação, usando perguntas diferentes.
    Use apenas dados presentes na mensagem original (animal, raça, tipo de produto).
    Corrija erros gramaticais, mas não invente nada novo.
    Se a mensagem já estiver clara, apenas retorne ela sem mudanças.
    Traga os produtos recuperados exatamente como retornados, sem alterações.
    Caso não encontre produtos válidos (com nome, descrição e link), diga: Infelizmente, não encontramos nenhum produto ideal para sua necessidade no momento. Você pode me dar mais detalhes para que eu possa buscar melhor?

    
  expected_output: >
    Pelo menos 2 Resultados recuperados do banco de dados vetorial exatamente como foi retornado,
    Caso o contexto não traga ao menos um produto válido (com name, link e description), a resposta deve ser: Infelizmente, não encontramos nenhum produto ideal para sua necessidade no momento. Você pode me dar mais detalhes para que eu possa buscar melhor?
    SEM QUALQUER MODIFICAÇÃO NOS RESULTADOS E METADADOS.
    SEMPRE RETORNE O LINK DOS PRODUTOS ENCONTRADOS.
  agent: consultor_vetorial

responder_cliente:
  description: >
    Use o contexto fornecido para responder a seguinte mensagem do usuário de forma clara e precisa: '{user_input}'. \n
    Caso não haja dados suficientes no contexto, informe que não foi possível econtrar o produto ideal, peça mais informações e fique à disposição do cliente.
    Responda apenas com base no conteúdo do contexto, mas nunca mencione ele. NUNCA INVENTE PRODUTOS.
    Sempre retorne o link do produto.
    Caso o cliente envie uma saudação ou agradecimentos/despedidas, apenas retribua e fique a disposição para ajudá-lo caso ele precise de mais apoio.
  expected_output: >
    Uma resposta direta e clara para a mensagem do usuário, sem incluir informações que não foram requisitadas pelo cliente.
    fundamentada somente no contexto apresentado e formatada em markdown.    
    Lembre-se que você está conversando com o cliente que está utilizando a plataforma e-commerce da PetLove, portanto direcione a mensagem como se voce fosse um assistente de compras conversando diretamente com ele. Converse com ele chamando-o em segunda pessoa.
  agent: assistente_vendas
