recuperar_contexto:
  description: >
    Verifique se é necessário recuperar contexto para responder a mensagem do usuário.
    Se não for necessário, então apenas finalize a resposta dizendo que não é necessário contexto.
    Caso seja necessario, então reformule a mensagem do usuário em uma standalone question, que deve ser objetiva e sem ambiguidade para extrair resultados de um banco de dados vetorial.\n
    Mensagem do usuário: '{user_input}'.\n
    Tente identificar qual é o animal/raça para qual o usuário precisa do produto. A raça e o animal são importantes para a busca, portanto adicione na standalone question caso seja possível identificar.
    Em seguida, use essa frase para consultar o banco e recuperar os trechos mais relevantes disponíveis.
    Se a query não trouxe resultados relevantes, reformule a frase e tente novamente.
    Use o histórico do chat para ajudar a reformular a mensagem do usuário.
  
  expected_output: >
    Pelo menos 4 Resultados recuperados do banco de dados vetorial exatamente como foi retornado,
    SEM QUALQUER MODIFICAÇÃO NOS RESULTADOS E METADADOS.
  agent: consultor_vetorial

responder_cliente:
  description: >
    Use o contexto fornecido para responder a seguinte mensagem do usuário de forma clara e precisa: '{user_input}'. \n
    Caso não haja dados suficientes no contexto, informe que não é possível responder a mensagem do usuário.
    Responda apenas com base no conteúdo do contexto, mas nunca mencione ele.
    Caso o cliente envie uma saudação ou agradecimentos/despedidas, apenas retribua e fique a disposição para ajudá-lo caso ele precise de mais apoio.
  expected_output: >
    Uma resposta direta e clara para a mensagem do usuário, sem incluir informações que não foram requisitadas pelo cliente.
    fundamentada somente no contexto apresentado e formatada em markdown.    
    Lembre-se que você está conversando com o cliente que está utilizando a plataforma e-commerce da PetLove, portanto direcione a mensagem como se voce fosse um assistente de compras conversando diretamente com ele. Converse com ele chamando-o em segunda pessoa.
  agent: assistente_vendas
